{{- range $key, $spec := .Values.gateways }}
{{- if ne $key "enabled" }}
{{- if $spec.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $key }}-service-account
  namespace: {{ $spec.namespace | default $.Release.Namespace }}
  labels:
    app: {{ $spec.labels.app }}
    chart: {{ template "gateway.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
---
{{- end }}
{{- end }}
{{- end }}

