apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "k8s-snapshots.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "k8s-snapshots.name" . }}
      annotations:
        # This annotation is needed to allow traffic to metadata.google.internal
        # until Istio's issue with FQDNs in ServiceEntries is not resolved:
        # https://github.com/istio/istio/issues/14404
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "169.254.169.254/32"
        {{ if .Values.serviceAccount }}accounts.google.com/service-account: {{ .Values.serviceAccount }}{{ end }}
        {{ if .Values.scopes }}accounts.google.com/scopes: {{ .Values.scopes }}{{ end }}
    spec:
      containers:
      - name: k8s-snapshots
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CLOUD_PROVIDER
            value: "google"
          - name: GCLOUD_CREDENTIALS_FILE
            value: ""
        {{- if .Values.useClaimName }}
          - name: USE_CLAIM_NAME
            value: "true"
        {{- end }}
    {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "k8s-snapshots.name" . }}
    {{- end }}
    {{- if .Values.runOnMasters }}
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/role: master
    {{- end }}
