apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "flowmanager.name" . }}-cert
  labels:
    app: {{ template "flowmanager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ template "flowmanager.name" . }}-tls
  issuerRef:
    name: letsencrypt-{{ template "flowmanager.name" . }}
    kind: Issuer
  dnsNames:
  {{ toYaml .Values.dnsNames | indent 2 | trim }}
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      {{ toYaml .Values.dnsNames | indent 6 | trim }}
