apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "flowmanager.name" . }}
spec:
  selector:
    app: flowmanager
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.svcListenPort }}
    targetPort: {{ .Values.flowmanagerListenPort }}
  type: ClusterIP
