{{- range $index, $value := .Values.secretLists }}
apiVersion: certmerge.lecentre.net/v1alpha1
kind: CertMerge
metadata:
  name: {{ include "certmerge-operator-crd.fullname" $ }}-{{ $index }}
  labels:
    app.kubernetes.io/name: {{ include "certmerge-operator-crd.name" $ }}
    helm.sh/chart: {{ include "certmerge-operator-crd.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  name: {{ $value.name | quote }}
  namespace: {{ $value.namespace }}
  secretlist:
  {{- range .secretlist }}
  - name: {{ .name | quote }}
    namespace: {{ .namespace | quote }}
  {{- end }}
  notify:
  {{- range .notify }}
  - name: {{ .name | quote }}
    namespace: {{ .namespace | quote }}
    type: {{ .type | quote }}
  {{- end }}
{{- end }}
