# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
default_docker: &default_docker
  docker:
  - image: gpii/exekube:0.9.4-google_gpii.0

version: 2
jobs:
  terraform-fmt-check:
    <<: *default_docker
    working_directory: /workspace
    steps:
      - checkout
      - run:
          name: Terraform Format Check
          command: |
            echo "Running Terraform format check...";
            terraform fmt --check=true /workspace

  gcp-unit-tests:
    <<: *default_docker
    working_directory: /workspace
    steps:
      - checkout
      - run:
          name: GCP Unit Tests
          # 'bundle install' must not use '--path. See Gemfile for more details.
          command: |
            echo "Running GCP unit tests...";
            cd /workspace/shared/rakefiles/tests;
            bundle install --with test;
            rake

workflows:
  version: 2
  main:
    jobs:
      - terraform-fmt-check
      - gcp-unit-tests
