apiVersion: v1
kind: Service
metadata:
  name: {{ template "couchdb.fullname" . }}
  labels:
    app: {{ template "couchdb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: http-couchdb
      port: 5984
    - name: tcp-epmd
      port: 4369
    - name: tcp-erl
      port: 9100
  selector:
    app: {{ template "couchdb.name" . }}
    release: {{ .Release.Name }}
