apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ template "devpmt.name" . }}-to-preferences
  labels:
    app: {{ template "devpmt.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
    {{- range $key, $value := .Values.preferences.labels }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "devpmt.name" . }}
    ports:
    - port: {{ .Values.preferences.port }}
      protocol: TCP
