{{- if .Values.morphic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "locust.fullname" . }}
  labels:
    app: {{ template "locust.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  morphic_client_id: {{ template "locust.defaultsecret" .Values.morphic.client_id }}
  morphic_client_secret: {{ template "locust.defaultsecret" .Values.morphic.client_secret }}
{{- end }}
