# Default values for couchdb-prometheus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

exporterListenPort: 9984

couchdb:
  uri: http://couchdb-svc-couchdb.default.svc.cluster.local:5984
  username: admin
  password: password
  databases: _all_dbs
  labels:
    app: couchdb
  port: http-couchdb

image:
  repository: gesellix/couchdb-prometheus-exporter
  tag: 22
  pullPolicy: IfNotPresent

prometheusToSdExporter:
  image:
    repository: gcr.io/google-containers/prometheus-to-sd
    tag: v0.5.1
    pullPolicy: IfNotPresent

## Optional resource requests and limits for deployment
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
   cpu: 10m
   memory: 60Mi
  limits:
   cpu: 10m
   memory: 60Mi
