apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "couchdb_prometheus_exporter.name" . }}-monitoring
spec:
  hosts:
  - monitoring.googleapis.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
