clusterSize: ${replica_count}

adminUsername: ${couchdb_admin_username}
adminPassword: ${couchdb_admin_password}
cookieAuthSecret: ${couchdb_auth_cookie}

helperImage:
  repository: ${couchdb_helper_repository}
  tag: ${couchdb_helper_tag}

initImage:
  repository: ${couchdb_init_repository}
  tag: ${couchdb_init_tag}

image:
  repository: ${couchdb_repository}
  tag: ${couchdb_tag}

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: "${pv_capacity}"
  storageClass: "${pv_storage_class}"
  provisioner: "${pv_provisioner}"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app"
              operator: In
              values:
              - couchdb
        topologyKey: "kubernetes.io/hostname"

couchdbConfig:
  chttpd:
    bind_address: any
    # http://docs.couchdb.org/en/stable/config/auth.html#authentication-configuration
    require_valid_user: true
  httpd:
    WWW-Authenticate: "Basic realm=\"CouchDB\""

resources:
  requests:
    cpu: ${requests_cpu}
    memory: ${requests_memory}
  limits:
    cpu: ${limits_cpu}
    memory: ${limits_memory}
