apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "service_account_assigner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "service_account_assigner.name" . }}
    helm.sh/chart: {{ include "service_account_assigner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
