apiVersion: v1
kind: Service
metadata:
  name: {{ template "preferences.name" . }}
  labels:
    app: {{ template "preferences.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "preferences.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.svcListenPort }}
    targetPort: {{ .Values.preferencesListenPort }}
  type: ClusterIP
