apiVersion: v1
kind: Secret
metadata:
  name: {{ template "productiontests.name" . }}
  labels:
    app: {{ template "productiontests.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  couchdbUrl: {{ template "productiontests.defaultsecret" .Values.couchdb.url }}
